### ISSUE TITLE
Large Text Box Error

### ISSUE THREAD

**Issue by OnionDev1885** [WybeNetwork/VistaPanel-Themes#13]
M using dark-discord theme.
It's very awesome.
The problem is that the large Text input boxes in SSL configure are errored.
They are with white background and text color as white too.

![Screenshot_2022-09-03-23-14-11-982_com android chrome](https://user-images.githubusercontent.com/81822450/188282350-da6e6753-df14-4e28-be3d-37b2478d7e50.jpg)

**Comment by 4yx** [comment]
Hey, thanks for the report and the kind words! I checked the dark-lite theme and was also able to replicate the issue there, so I'll be checking and updating all dark themes soon.

**Comment by OnionDev1885** [comment]
Thank you
I loved your both projects: VPT and VPC
Great work. That's again

**Comment by OnionDev1885** [comment]
Found another one in DNS tab
![image](https://user-images.githubusercontent.com/81822450/188325437-787fd455-3525-464a-a9bf-bd0b2d8afd1d.png)

**Comment by 4yx** [comment]
@OnionDev1885 sorry it took me so long! Can you see if the issue was fixed?

**Comment by OnionDev1885** [comment]
The SSL one is fixed but cname one is still errored

**Comment by 4yx** [comment]
That is very strange, I am unable to replicate this by loading the themes on a clean (without any other code) reseller. I tried to sign up for yours but Xera seems to be broken, is there any way you could make me a test account to see it on your panel?

My Discord is ```᲼᲼#9121```, if you can't add me because of the invisible username I can be found in the [iFastNet Community](https://dsc.gg/ifastnet), or you can email the credentials on ```anyxp@protonmail.com``` if you prefer that.

**Comment by mahofficial** [comment]
I believe the issue should be fixed by now. As it was because of default JS adding background color property directly to the element with white color. Kindly check and confirm.

**Comment by mahofficial** [comment]
I am closing this issue for now with 4ef83edf419252a098fb12570123941216f5760d

**Comment by 4yx** [comment]
Which JS code was causing it? I find it strange I couldn't replicate it on my MOFH accounts.

**Comment by mahofficial** [comment]
> Which JS code was causing it? 

I believe the default one maybe



> I find it strange I couldn't replicate it on my MOFH accounts.

Actually, I was able to replicate it, it was only happening when you click on the field

![image](https://user-images.githubusercontent.com/25408054/189204382-dd844ce0-f579-4d87-9956-4c130e918a4d.png)
