### ISSUE TITLE
Responsiveness issue in Dark Theme

### ISSUE THREAD

**Issue by aa22dev** [WybeNetwork/VistaPanel-Themes#20]
Possible Issues:
- Domain Checker search bar not responsive (size is fixed)
- Account Table size causes responsiveness issue

![vPanel Dark Theme](https://media.discordapp.net/attachments/1063499125456388186/1065366580504035378/Screenshot_20230118-212607.jpg?width=648&height=1220)

Issue Reported on Discord by BastelPichi

**Comment by aa22dev** [comment]
> Unless I'm missing something, that has been a known issue since a long time, and exists because of the way iFastNet coded the domain search in the panel. In fact, it is the sole reason https://github.com/WybeNetwork/VistaPanel-Customizations/tree/master/responsive-domain-search exists, as it was created to address this problem and has successfully done so.
> I tested the Dark theme with responsive-domain-search and it worked perfectly.

Yes you are actually right but If I'll find a time, then I'll fix the responsiveness issue of domain search bar directly using CSS.

> I am uncertain if we should patch the other themes to include this fix, however, considering Responsive Domain Search does that job well. In any case, we can discuss this.

Actually, If this fix is directly implemented in CSS then an extra HTTP request can be avoided.

> I am unable to replicate this. Can you show an example?

I'm attaching the screenshot
![image](https://user-images.githubusercontent.com/25408054/213721385-cfe3297c-ecc7-4544-83d5-f4e97b763fe6.png)

In this screen you can see that the stats table wanted to maintain it's size instead because of the long text, if we want to fix this issue then only one line of CSS code should be added to the file, which I might add soon.

**Comment by 4yx** [comment]
> If I'll find a time, then I'll fix the responsiveness issue of domain search bar directly using CSS.

Alright, I won't protest this, if possible just make sure that it won't break Responsive Domain Search :D

> if we want to fix this issue then only one line of CSS code should be added to the file, which I might add soon.

Nice!

**Comment by aa22dev** [comment]
Closing as fixed in #26

**Comment by aa22dev** [comment]
Closing as fixed in #26
