### ISSUE TITLE
Link is expired

### ISSUE THREAD

**Issue by MS-DOS2** [WybeNetwork/VistaPanel-Themes#8]
Hello,
The links of the theme switcher style files are invalid 
https://cdn.vptofficial.me/light-lite/styles.css
https://cdn.vptofficial.me/gradient-blue-lite/styles.css
https://cdn.vptofficial.me/dark-lite/styles.css
Impossible to change the theme do you have other links?

**Comment by mahofficial** [comment]
Hi, we now have new CDN links. Kindly use it.
https://vpt.cdn.wybenetwork.com/

for themes you need the URL will be:
https://vpt.cdn.wybenetwork.com/light-lite/styles.css
https://vpt.cdn.wybenetwork.com/gradient-blue-lite/styles.css
https://vpt.cdn.wybenetwork.com/dark-lite/styles.css
